### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by Melissa941** [Some-Cool-Name/Social-Media-Market-Place-Clone-Project#25]
![Screenshot (6)](https://user-images.githubusercontent.com/76457753/115287726-e5cff980-a150-11eb-8be9-a3b046021471.png)
![Screenshot (7)](https://user-images.githubusercontent.com/76457753/115287757-ebc5da80-a150-11eb-8bc2-ba29fee6a234.png)

![ClientServerDiagram](https://user-images.githubusercontent.com/65238369/117673294-f6511e00-b1aa-11eb-9d8d-981cb38ea91c.png)

**Comment by othnielNgobeni** [comment]
![Deployment Diagram (1)](https://user-images.githubusercontent.com/81512981/117530954-4760e680-afe0-11eb-8461-1c7c148ef95c.png)

**Comment by othnielNgobeni** [comment]
![Use Case Diagram(2)](https://user-images.githubusercontent.com/65238369/122258207-12925a00-ced1-11eb-99b2-51d238ee17c2.png)
![Untitled Diagram (6)](https://user-images.githubusercontent.com/81512981/117627898-df91d380-b178-11eb-9916-0aa41792857b.png)

**Comment by ThandoAmatullah** [comment]
![1620653483447](https://user-images.githubusercontent.com/65238369/117667338-17167500-b1a5-11eb-815f-df29620990db.jpg)
![1620653483451](https://user-images.githubusercontent.com/65238369/117667347-18e03880-b1a5-11eb-9562-3053b0c83b32.jpg)
![1620653483456](https://user-images.githubusercontent.com/65238369/117667354-1aa9fc00-b1a5-11eb-9554-ad0ecf25c771.jpg)
![1620653483460](https://user-images.githubusercontent.com/65238369/117667363-1bdb2900-b1a5-11eb-82a3-fd4987d15513.jpg)
![1620653483465](https://user-images.githubusercontent.com/65238369/117667372-1da4ec80-b1a5-11eb-8b82-f81aedd50433.jpg)
