### ISSUE TITLE
Uploading Pictures

### ISSUE THREAD

**Issue by Melissa941** [Some-Cool-Name/Social-Media-Market-Place-Clone-Project#33]
![first](https://user-images.githubusercontent.com/76457753/118105939-58916500-b3dd-11eb-99cc-5a4a64977640.png)

**Comment by Melissa941** [comment]
![Second](https://user-images.githubusercontent.com/76457753/118106355-ce95cc00-b3dd-11eb-8bb3-57370b969f27.png)

**Comment by Melissa941** [comment]
![Thrid](https://user-images.githubusercontent.com/76457753/118106656-1caacf80-b3de-11eb-8cff-a40cee70bb7f.png)

**Comment by ThandoAmatullah** [comment]
![Deployement Diagram](https://user-images.githubusercontent.com/65238369/119253840-5d130600-bbb3-11eb-8d20-ed2ef1806000.png)
![Use Case Diagram(1)](https://user-images.githubusercontent.com/65238369/119253846-5edcc980-bbb3-11eb-98cc-825f16655748.png)
