### ISSUE TITLE
Feed Page Design

### ISSUE THREAD

**Issue by ThandoAmatullah** [Some-Cool-Name/Social-Media-Market-Place-Clone-Project#35]
@Melissa941  The interests are not showing on the users feed.

**Comment by Melissa941** [comment]
![Feed1](https://user-images.githubusercontent.com/76457753/118513477-08dfd000-b734-11eb-8a29-53ec3e8f2779.png)

**Comment by Melissa941** [comment]
![info1](https://user-images.githubusercontent.com/76457753/118513765-4f352f00-b734-11eb-8cf6-8de557a10ea8.png)
